export const dataClone = [
  {
    OrgID: "7206207001",
    CustomerCodeSys: "CTMCS.D65.00044",
    NetworkID: "7206207001",
    CustomerCode: "TESTING",
    CustomerType: null,
    CustomerGrpCode: null,
    CustomerSourceCode: null,
    CustomerName: "Testing",
    CustomerNameEN: null,
    CustomerGender: null,
    CustomerPhoneNo: null,
    CustomerMobilePhone: null,
    ProvinceCode: null,
    DistrictCode: null,
    WardCode: null,
    AreaCode: null,
    CustomerAvatarName: null,
    CustomerAvatarSpec: null,
    FlagCustomerAvatarPath: null,
    CustomerAvatarPath: null,
    JsonCustomerInfo:
      '[{"ColCodeSys":"COLD63042","ColValue":"0123456789"},{"ColCodeSys":"COLD63049","ColValue":"tienanh17082001@gmail.com"},{"ColCodeSys":"COLD66120","ColValue":"KHver2"},{"ColCodeSys":"COLD68227","ColValue":"Nam"},{"ColCodeSys":"COLD68257","ColValue":"name"},{"ColCodeSys":"COLD69141","ColValue":"1"}]',
    MyXml: null,
    CustomerAddress: null,
    CustomerEmail: null,
    CustomerDateOfBirth: null,
    GovIDType: null,
    GovIDCardNo: null,
    GovIDCardDate: null,
    GovIDCardPlace: null,
    TaxCode: null,
    BankCode: null,
    BankName: null,
    BankAccountNo: null,
    RepresentName: null,
    RepresentPosition: null,
    UserCodeOwner: null,
    ContactName: null,
    ContactPhone: "0123456789",
    ContactEmail: "email",
    Fax: null,
    Facebook: null,
    InvoiceCustomerName: null,
    InvoiceCustomerAddress: null,
    InvoiceOrgName: null,
    InvoiceEmailSend: null,
    MST: null,
    ListOfCustDynamicFieldValue: null,
    FlagDealer: null,
    FlagSupplier: null,
    FlagEndUser: null,
    FlagShipper: null,
    FlagBank: null,
    FlagInsurrance: null,
    DTimeUsed: null,
    CreateDTimeUTC: "2023-06-05 03:45:55",
    CreateBy: "0317844394@INOS.VN",
    LUDTimeUTC: "2023-06-05 03:45:55",
    LUBy: "0317844394@INOS.VN",
    FlagActive: "1",
    Remark: null,
    Coordinates: null,
    LogLUDTimeUTC: "2023-06-14 10:37:31",
    LogLUBy: "0317844394@INOS.VN",
    CustomerCodeSysERP: null,
    mcerp_CustomerName: null,
    Org_NNTFullName: "CÔNG TY CỔ PHẦN QUỐC TẾ LONG QUANG",
    Network_NNTFullName: "CÔNG TY CỔ PHẦN QUỐC TẾ LONG QUANG",
    mct_CustomerTypeName: null,
    mcg_CustomerGrpName: null,
    mcs_CustomerSourceName: null,
    mp_ProvinceName: null,
    md_DistrictName: null,
    mw_WardName: null,
    ma_AreaName: null,
    mg_GovIDTypeName: null,
    SolutionCode: null,
    FunctionActionType: null,
    Setting: null,
    CustomDataDict: {},
  },
  {
    OrgID: "7206207001",
    CustomerCodeSys: "CTMCS.D65.00045",
    NetworkID: "7206207001",
    CustomerCode: "KH202306051114",
    CustomerType: null,
    CustomerGrpCode: null,
    CustomerSourceCode: null,
    CustomerName: "Chu Tiến Anh",
    CustomerNameEN: null,
    CustomerGender: null,
    CustomerPhoneNo: null,
    CustomerMobilePhone: null,
    ProvinceCode: null,
    DistrictCode: null,
    WardCode: null,
    AreaCode: null,
    CustomerAvatarName: null,
    CustomerAvatarSpec: null,
    FlagCustomerAvatarPath: null,
    CustomerAvatarPath: null,
    JsonCustomerInfo:
      '[{"ColCodeSys":"COLD63039","ColValue":"Khách hàng 12"},{"ColCodeSys":"COLD63042","ColValue":"0123567912"},{"ColCodeSys":"COLD63044","ColValue":"Đối tượng 12"},{"ColCodeSys":"COLD63046","ColValue":"Chức vụ 1222"},{"ColCodeSys":"COLD63049","ColValue":"tienanh170820021@gmail.com"},{"ColCodeSys":"COLD63068","ColValue":"AREACODE.230531C"}]',
    MyXml: null,
    CustomerAddress: null,
    CustomerEmail: null,
    CustomerDateOfBirth: null,
    GovIDType: null,
    GovIDCardNo: null,
    GovIDCardDate: null,
    GovIDCardPlace: null,
    TaxCode: null,
    BankCode: null,
    BankName: null,
    BankAccountNo: null,
    RepresentName: null,
    RepresentPosition: null,
    UserCodeOwner: null,
    ContactName: null,
    ContactPhone: null,
    ContactEmail: null,
    Fax: null,
    Facebook: null,
    InvoiceCustomerName: null,
    InvoiceCustomerAddress: null,
    InvoiceOrgName: null,
    InvoiceEmailSend: null,
    MST: null,
    ListOfCustDynamicFieldValue: null,
    FlagDealer: null,
    FlagSupplier: null,
    FlagEndUser: null,
    FlagShipper: null,
    FlagBank: null,
    FlagInsurrance: null,
    DTimeUsed: null,
    CreateDTimeUTC: "2023-06-05 04:18:51",
    CreateBy: "0317844394@INOS.VN",
    LUDTimeUTC: "2023-06-05 04:18:51",
    LUBy: "0317844394@INOS.VN",
    FlagActive: "1",
    Remark: null,
    Coordinates: null,
    LogLUDTimeUTC: "2023-06-05 07:39:29",
    LogLUBy: "0317844394@INOS.VN",
    CustomerCodeSysERP: null,
    mcerp_CustomerName: null,
    Org_NNTFullName: "CÔNG TY CỔ PHẦN QUỐC TẾ LONG QUANG",
    Network_NNTFullName: "CÔNG TY CỔ PHẦN QUỐC TẾ LONG QUANG",
    mct_CustomerTypeName: null,
    mcg_CustomerGrpName: null,
    mcs_CustomerSourceName: null,
    mp_ProvinceName: null,
    md_DistrictName: null,
    mw_WardName: null,
    ma_AreaName: null,
    mg_GovIDTypeName: null,
    SolutionCode: null,
    FunctionActionType: null,
    Setting: null,
    CustomDataDict: {},
  },
];
