import { useI18n } from "@/i18n/useI18n";
import { useClientgateApi } from "@/packages/api";
import { useAuth } from "@/packages/contexts/auth";
import { showErrorAtom } from "@/packages/store";
import { localeAtom } from "@/packages/store/localization-store";

import { useQuery } from "@tanstack/react-query";
import { Button } from "devextreme-react";
import { useAtom, useSetAtom } from "jotai";
import { useState } from "react";
import { toast } from "react-toastify";
import * as XLSX from "xlsx";
import { jsonData } from "./list-dynamic-field";

const data = [
  {
    ColCaption: "Doanh thu",
    ColDataType: "SELECTONEDROPDOWN",
    JsonListOption:
      '[{"Value":"Dưới 3 tỉ đồng","IsSelected":false,"id":"","OrderIdx":0},{"Value":"Từ 3-10 tỉ đồng","IsSelected":false,"id":"","OrderIdx":1},{"Value":"Từ 10 - 100 tỉ đồng","IsSelected":false,"id":"","OrderIdx":2},{"Value":"Trên 100 tỉ đồng","IsSelected":false,"id":"","OrderIdx":3}]',
  },
  {
    ColCaption: "Quy mô nhân sự",
    ColDataType: "SELECTONEDROPDOWN",
    JsonListOption:
      '[{"Value":"Dưới 10","IsSelected":false,"id":"","OrderIdx":0},{"Value":"Từ 10 - 100 ","IsSelected":false,"id":"","OrderIdx":1},{"Value":"Từ 100 - 200","IsSelected":false,"id":"","OrderIdx":2},{"Value":"Từ 200 - 1000","IsSelected":false,"id":"","OrderIdx":3},{"Value":"Trên 1000","IsSelected":false,"id":"","OrderIdx":4}]',
  },
  {
    ColCaption: "Chức vụ",
    ColDataType: "TEXT",
    JsonListOption: "[]",
  },
  {
    ColCaption: "Giới tính",
    ColDataType: "SELECTONERADIO",
    JsonListOption:
      '[{"Value":"Nam","IsSelected":true,"id":"","OrderIdx":0},{"Value":"Nữ","IsSelected":false,"id":"","OrderIdx":1},{"Value":"Khác","IsSelected":false,"id":"","OrderIdx":2}]',
  },
  {
    ColCaption: "Ngày sinh",
    ColDataType: "DATE",
    JsonListOption: "[]",
  },
  {
    ColCaption: "Số giấy tờ",
    ColDataType: "TEXT",
    JsonListOption: "[]",
  },
  {
    ColCaption: "Loại giấy tờ",
    ColDataType: "SELECTONEDROPDOWN",
    JsonListOption:
      '[{"Value":"CCCD","IsSelected":false,"id":"","OrderIdx":0},{"Value":"CMND","IsSelected":false,"id":"","OrderIdx":1}]',
  },
  {
    ColCaption: "Ngành nghề",
    ColDataType: "SELECTONEDROPDOWN",
    JsonListOption:
      '[{"Value":"Nhóm ngành sản xuất và chế biến","IsSelected":false,"id":"","OrderIdx":0},{"Value":"Nhóm ngành kiến trúc và xây dựng","IsSelected":false,"id":"","OrderIdx":1},{"Value":"Nhóm những ngành kinh doanh","IsSelected":false,"id":"","OrderIdx":2},{"Value":"Nhóm các ngành công nghệ - thông tin","IsSelected":false,"id":"","OrderIdx":3},{"Value":"Nhóm ngành luật - nhân văn","IsSelected":false,"id":"","OrderIdx":4},{"Value":"Nhóm ngành nghệ thuật - thẩm mỹ - đồ họa","IsSelected":false,"id":"","OrderIdx":5},{"Value":"Nhóm ngành báo chí - khoa học và xã hội","IsSelected":false,"id":"","OrderIdx":6},{"Value":"Nhóm ngành khoa học cơ bản","IsSelected":false,"id":"","OrderIdx":7},{"Value":"Nhóm ngành Sư phạm","IsSelected":false,"id":"","OrderIdx":8},{"Value":"Nhóm ngành nông - lâm - ngư nghiệp","IsSelected":false,"id":"","OrderIdx":9}]',
  },
  {
    ColCaption: "Ghi chú",
    ColDataType: "TEXTAREA",
    JsonListOption: "[]",
  },
  {
    ColCaption: "Địa chỉ",
    ColDataType: "TEXTAREA",
    JsonListOption: "[]",
  },
  {
    ColCaption: "Mã bưu chính",
    ColDataType: "TEXT",
    JsonListOption: "[]",
  },
  {
    ColCaption: "Website",
    ColDataType: "TEXT",
    JsonListOption: "[]",
  },
  {
    ColCaption: "Số tài khoản",
    ColDataType: "TEXT",
    JsonListOption: "[]",
  },
  {
    ColCaption: "Ngân hàng",
    ColDataType: "TEXT",
    JsonListOption: "[]",
  },
  {
    ColCaption: "Điều khoản bán hàng",
    ColDataType: "MASTERDATA",
    JsonListOption: '[{"Value":"Mst_PaymentTerm"}]',
  },
  {
    ColCaption: "Tài khoản công nợ phải thu",
    ColDataType: "TEXT",
    JsonListOption: "[]",
  },
  {
    ColCaption: "Tài khoản công nợ phải trả",
    ColDataType: "TEXT",
    JsonListOption: "[]",
  },
  {
    ColCaption: "Điều khoản mua hàng",
    ColDataType: "MASTERDATA",
    JsonListOption: '[{"Value":"Mst_PaymentTerm"}]',
  },
  {
    ColCaption: "Tên đơn vị",
    ColDataType: "TEXT",
    JsonListOption: "[]",
  },
  {
    ColCaption: "Người mua hàng",
    ColDataType: "TEXT",
    JsonListOption: "[]",
  },
  {
    ColCaption: "Email nhận HĐ",
    ColDataType: "TEXT",
    JsonListOption: "[]",
  },
  {
    ColCaption: "Địa chỉ đầy đủ (Hóa đơn)",
    ColDataType: "TEXTAREA",
    JsonListOption: "[]",
  },
  {
    ColCaption: "Số nhà, Đường phố (Hóa đơn)",
    ColDataType: "TEXT",
    JsonListOption: "[]",
  },
  {
    ColCaption: "Mã bưu chính (Hóa đơn)",
    ColDataType: "TEXT",
    JsonListOption: "[]",
  },
  {
    ColCaption: "Số nhà, Đường phố (Giao hàng)",
    ColDataType: "TEXT",
    JsonListOption: "[]",
  },
  {
    ColCaption: "Địa chỉ (Giao hàng)",
    ColDataType: "TEXT",
    JsonListOption: "[]",
  },
  {
    ColCaption: "Fax",
    ColDataType: "TEXT",
    JsonListOption: "[]",
  },
  {
    ColCaption: "GLN",
    ColDataType: "TEXT",
    JsonListOption: "[]",
  },
  {
    ColCaption: "Vị trí",
    ColDataType: "TEXT",
    JsonListOption: "[]",
  },
  {
    ColCaption: "UserID ( của KH)",
    ColDataType: "TEXT",
    JsonListOption: "[]",
  },
  {
    ColCaption: "OrgID",
    ColDataType: "TEXT",
    JsonListOption: "[]",
  },
  {
    ColCaption: "NetworkID",
    ColDataType: "TEXT",
    JsonListOption: "[]",
  },
  {
    ColCaption: "Loại hình",
    ColDataType: "SELECTONEDROPDOWN",
    JsonListOption:
      '[{"Value":"Công ty trách nhiệm hữu hạn 1 thành viên","IsSelected":false,"id":"","OrderIdx":0},{"Value":"Công ty trách nhiệm hữu hạn 2 thành viên trở lên","IsSelected":false,"id":"","OrderIdx":1},{"Value":"Doanh nghiệp hợp danh","IsSelected":false,"id":"","OrderIdx":2},{"Value":"Công ty cổ phần","IsSelected":false,"id":"","OrderIdx":3},{"Value":"Doanh nghiệp tư nhân","IsSelected":false,"id":"","OrderIdx":4},{"Value":"Doanh nghiệp có trách nhiệm vô hạn","IsSelected":false,"id":"","OrderIdx":5},{"Value":"Doanh nghiệp có trách nhiệm hữu hạn","IsSelected":false,"id":"","OrderIdx":6}]',
  },
  {
    ColCaption: "Số nhà, Đường phố ( Liên hệ)",
    ColDataType: "TEXTAREA",
    JsonListOption: "[]",
  },
  {
    ColCaption: "Vùng thị trường",
    ColDataType: "MASTERDATA",
    JsonListOption: '[{"Value":"Mst_Area"}]',
  },
  {
    ColCaption: "Mã bưu chính ( Giao hàng)",
    ColDataType: "TEXT",
    JsonListOption: "[]",
  },
  {
    ColCaption: "NetworkID",
    ColDataType: "TEXT",
    JsonListOption: "[]",
  },
  {
    ColCaption: "Là khách hàng từ ngày",
    ColDataType: "DATE",
    JsonListOption: "[]",
  },
  {
    ColCaption: "Tên viết tắt",
    ColDataType: "TEXT",
    JsonListOption: "[]",
  },
  {
    ColCaption: "Nguồn khách",
    ColDataType: "SELECTONEDROPDOWN",
    JsonListOption:
      '[{"Value":"Mối quan hệ cá nhân","IsSelected":false,"id":"","OrderIdx":0},{"Value":"Thông qua các công cụ tìm kiếm","IsSelected":false,"id":"","OrderIdx":1},{"Value":"Thông qua hội thảo","IsSelected":false,"id":"","OrderIdx":2},{"Value":"Qua kênh Telesales","IsSelected":false,"id":"","OrderIdx":3},{"Value":"Mạng xã hội","IsSelected":false,"id":"","OrderIdx":4},{"Value":"Nghiên cứu đối thủ cạnh tranh","IsSelected":false,"id":"","OrderIdx":5}]',
  },
];

const screenDTL = [
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "CGCS.CTM.DTL.2023",
    ColCodeSys: "CustomerCode",
    NetworkID: "6451164000",
    ColOperatorType: "LIKE",
    OrderIdx: 1,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "1",
    FlagIsCheckDuplicate: "1",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:33:58",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "CustomerCode",
    ColCaption: "Mã khách hàng",
    ColDataType: "TEXT",
    FlagIsColDynamic: "0",
    SqlOperatorType: "like",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "CGCS.CTM.DTL.2023",
    ColCodeSys: "C005",
    NetworkID: "6451164000",
    ColOperatorType: "LIKE",
    OrderIdx: 2,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "0",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:33:58",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "C004",
    ColCaption: "Chức vụ",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "like",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "CGCS.CTM.DTL.2023",
    ColCodeSys: "CustomerName",
    NetworkID: "6451164000",
    ColOperatorType: "LIKE",
    OrderIdx: 3,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "1",
    FlagIsCheckDuplicate: "1",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:33:58",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "CustomerName",
    ColCaption: "Tên khách hàng",
    ColDataType: "TEXT",
    FlagIsColDynamic: "0",
    SqlOperatorType: "like",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "CGCS.CTM.DTL.2023",
    ColCodeSys: "CustomerCodeSysERP",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 4,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "1",
    FlagIsCheckDuplicate: "1",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:33:58",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "CustomerCodeSysERP",
    ColCaption: "Doanh nghiệp",
    ColDataType: "CUSTOMERCODESYSERP",
    FlagIsColDynamic: "0",
    SqlOperatorType: "=",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "CGCS.CTM.DTL.2023",
    ColCodeSys: "CtmPhoneNo",
    NetworkID: "6451164000",
    ColOperatorType: "LIKE",
    OrderIdx: 5,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "1",
    FlagIsCheckDuplicate: "1",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:33:58",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "CtmPhoneNo",
    ColCaption: "Phone",
    ColDataType: "PHONE",
    FlagIsColDynamic: "0",
    SqlOperatorType: "like",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "CGCS.CTM.DTL.2023",
    ColCodeSys: "CtmEmail",
    NetworkID: "6451164000",
    ColOperatorType: "LIKE",
    OrderIdx: 6,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "1",
    FlagIsCheckDuplicate: "1",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:33:58",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "CtmEmail",
    ColCaption: "Email",
    ColDataType: "EMAIL",
    FlagIsColDynamic: "0",
    SqlOperatorType: "like",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
];

const screenAdd = [
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.01",
    ColCodeSys: "CustomerType",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 1,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "1",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "CustomerType",
    ColCaption: "Loại khách hàng",
    ColDataType: "CUSTOMERTYPE",
    FlagIsColDynamic: "0",
    SqlOperatorType: "=",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.01",
    ColCodeSys: "PartnerType",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 2,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "1",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "PartnerType",
    ColCaption: "Đối Tượng",
    ColDataType: "PARTNERTYPE",
    FlagIsColDynamic: "0",
    SqlOperatorType: "=",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.01",
    ColCodeSys: "CustomerCode",
    NetworkID: "6451164000",
    ColOperatorType: "LIKE",
    OrderIdx: 3,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "1",
    FlagIsCheckDuplicate: "1",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "CustomerCode",
    ColCaption: "Mã khách hàng",
    ColDataType: "TEXT",
    FlagIsColDynamic: "0",
    SqlOperatorType: "like",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.01",
    ColCodeSys: "C005",
    NetworkID: "6451164000",
    ColOperatorType: "LIKE",
    OrderIdx: 4,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "0",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "C004",
    ColCaption: "Chức vụ",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "like",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.01",
    ColCodeSys: "CustomerName",
    NetworkID: "6451164000",
    ColOperatorType: "LIKE",
    OrderIdx: 5,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "1",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "CustomerName",
    ColCaption: "Tên khách hàng",
    ColDataType: "TEXT",
    FlagIsColDynamic: "0",
    SqlOperatorType: "like",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.01",
    ColCodeSys: "CustomerCodeSysERP",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 6,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "CustomerCodeSysERP",
    ColCaption: "Doanh nghiệp",
    ColDataType: "CUSTOMERCODESYSERP",
    FlagIsColDynamic: "0",
    SqlOperatorType: "=",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.01",
    ColCodeSys: "CtmPhoneNo",
    NetworkID: "6451164000",
    ColOperatorType: "LIKE",
    OrderIdx: 7,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "CtmPhoneNo",
    ColCaption: "Phone",
    ColDataType: "PHONE",
    FlagIsColDynamic: "0",
    SqlOperatorType: "like",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.01",
    ColCodeSys: "CtmEmail",
    NetworkID: "6451164000",
    ColOperatorType: "LIKE",
    OrderIdx: 8,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "CtmEmail",
    ColCaption: "Email",
    ColDataType: "EMAIL",
    FlagIsColDynamic: "0",
    SqlOperatorType: "like",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.01",
    ColCodeSys: "C0RO",
    NetworkID: "6451164000",
    ColOperatorType: "LIKE",
    OrderIdx: 9,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "0",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "C0RN",
    ColCaption: "Tên viết tắt",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "like",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.01",
    ColCodeSys: "C007",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 10,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "C006",
    ColCaption: "Giới tính",
    ColDataType: "SELECTONERADIO",
    FlagIsColDynamic: "1",
    SqlOperatorType: "=",
    mdmc_JsonListOption:
      '[{"Value":"Nam","IsSelected":true,"id":"","OrderIdx":0},{"Value":"Nữ","IsSelected":false,"id":"","OrderIdx":1},{"Value":"Khác","IsSelected":false,"id":"","OrderIdx":2}]',
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.01",
    ColCodeSys: "MST",
    NetworkID: "6451164000",
    ColOperatorType: "LIKE",
    OrderIdx: 11,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "MST",
    ColCaption: "MST",
    ColDataType: "TEXT",
    FlagIsColDynamic: "0",
    SqlOperatorType: "like",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.01",
    ColCodeSys: "C009",
    NetworkID: "6451164000",
    ColOperatorType: "RANGE",
    OrderIdx: 12,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "C008",
    ColCaption: "Ngày sinh",
    ColDataType: "DATE",
    FlagIsColDynamic: "1",
    SqlOperatorType: "=>;<=",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.01",
    ColCodeSys: "CustomerGrpCode",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 13,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "CustomerGrpCode",
    ColCaption: "Nhóm khách hàng",
    ColDataType: "CUSTOMERGROUP",
    FlagIsColDynamic: "0",
    SqlOperatorType: "=",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.01",
    ColCodeSys: "C00B",
    NetworkID: "6451164000",
    ColOperatorType: "LIKE",
    OrderIdx: 14,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "C00A",
    ColCaption: "Số giấy tờ",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "like",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.01",
    ColCodeSys: "C0RR",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 15,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "C0RP",
    ColCaption: "Nguồn khách",
    ColDataType: "SELECTONEDROPDOWN",
    FlagIsColDynamic: "1",
    SqlOperatorType: "=",
    mdmc_JsonListOption:
      '[{"Value":"Mối quan hệ cá nhân","IsSelected":false,"id":"","OrderIdx":0},{"Value":"Thông qua các công cụ tìm kiếm","IsSelected":false,"id":"","OrderIdx":1},{"Value":"Thông qua hội thảo","IsSelected":false,"id":"","OrderIdx":2},{"Value":"Qua kênh Telesales","IsSelected":false,"id":"","OrderIdx":3},{"Value":"Mạng xã hội","IsSelected":false,"id":"","OrderIdx":4},{"Value":"Nghiên cứu đối thủ cạnh tranh","IsSelected":false,"id":"","OrderIdx":5}]',
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.01",
    ColCodeSys: "C00D",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 16,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "C00C",
    ColCaption: "Loại giấy tờ",
    ColDataType: "SELECTONEDROPDOWN",
    FlagIsColDynamic: "1",
    SqlOperatorType: "=",
    mdmc_JsonListOption:
      '[{"Value":"CCCD","IsSelected":false,"id":"","OrderIdx":0},{"Value":"CMND","IsSelected":false,"id":"","OrderIdx":1}]',
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.01",
    ColCodeSys: "C04W",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 17,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "C04V",
    ColCaption: "Loại hình",
    ColDataType: "SELECTONEDROPDOWN",
    FlagIsColDynamic: "1",
    SqlOperatorType: "=",
    mdmc_JsonListOption:
      '[{"Value":"Công ty trách nhiệm hữu hạn 1 thành viên","IsSelected":false,"id":"","OrderIdx":0},{"Value":"Công ty trách nhiệm hữu hạn 2 thành viên trở lên","IsSelected":false,"id":"","OrderIdx":1},{"Value":"Doanh nghiệp hợp danh","IsSelected":false,"id":"","OrderIdx":2},{"Value":"Công ty cổ phần","IsSelected":false,"id":"","OrderIdx":3},{"Value":"Doanh nghiệp tư nhân","IsSelected":false,"id":"","OrderIdx":4},{"Value":"Doanh nghiệp có trách nhiệm vô hạn","IsSelected":false,"id":"","OrderIdx":5},{"Value":"Doanh nghiệp có trách nhiệm hữu hạn","IsSelected":false,"id":"","OrderIdx":6}]',
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.01",
    ColCodeSys: "C00F",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 18,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "C00E",
    ColCaption: "Ngành nghề",
    ColDataType: "SELECTONEDROPDOWN",
    FlagIsColDynamic: "1",
    SqlOperatorType: "=",
    mdmc_JsonListOption:
      '[{"Value":"Nhóm ngành sản xuất và chế biến","IsSelected":false,"id":"","OrderIdx":0},{"Value":"Nhóm ngành kiến trúc và xây dựng","IsSelected":false,"id":"","OrderIdx":1},{"Value":"Nhóm những ngành kinh doanh","IsSelected":false,"id":"","OrderIdx":2},{"Value":"Nhóm các ngành công nghệ - thông tin","IsSelected":false,"id":"","OrderIdx":3},{"Value":"Nhóm ngành luật - nhân văn","IsSelected":false,"id":"","OrderIdx":4},{"Value":"Nhóm ngành nghệ thuật - thẩm mỹ - đồ họa","IsSelected":false,"id":"","OrderIdx":5},{"Value":"Nhóm ngành báo chí - khoa học và xã hội","IsSelected":false,"id":"","OrderIdx":6},{"Value":"Nhóm ngành khoa học cơ bản","IsSelected":false,"id":"","OrderIdx":7},{"Value":"Nhóm ngành Sư phạm","IsSelected":false,"id":"","OrderIdx":8},{"Value":"Nhóm ngành nông - lâm - ngư nghiệp","IsSelected":false,"id":"","OrderIdx":9}]',
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.01",
    ColCodeSys: "C001",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 19,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "C000",
    ColCaption: "Doanh thu",
    ColDataType: "SELECTONEDROPDOWN",
    FlagIsColDynamic: "1",
    SqlOperatorType: "=",
    mdmc_JsonListOption:
      '[{"Value":"Dưới 3 tỉ đồng","IsSelected":false,"id":"","OrderIdx":0},{"Value":"Từ 3-10 tỉ đồng","IsSelected":false,"id":"","OrderIdx":1},{"Value":"Từ 10 - 100 tỉ đồng","IsSelected":false,"id":"","OrderIdx":2},{"Value":"Trên 100 tỉ đồng","IsSelected":false,"id":"","OrderIdx":3}]',
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.01",
    ColCodeSys: "C00H",
    NetworkID: "6451164000",
    ColOperatorType: "LIKE",
    OrderIdx: 20,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "C00G",
    ColCaption: "Ghi chú",
    ColDataType: "TEXTAREA",
    FlagIsColDynamic: "1",
    SqlOperatorType: "like",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.01",
    ColCodeSys: "C003",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 21,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "C002",
    ColCaption: "Quy mô nhân sự",
    ColDataType: "SELECTONEDROPDOWN",
    FlagIsColDynamic: "1",
    SqlOperatorType: "=",
    mdmc_JsonListOption:
      '[{"Value":"Dưới 10","IsSelected":false,"id":"","OrderIdx":0},{"Value":"Từ 10 - 100 ","IsSelected":false,"id":"","OrderIdx":1},{"Value":"Từ 100 - 200","IsSelected":false,"id":"","OrderIdx":2},{"Value":"Từ 200 - 1000","IsSelected":false,"id":"","OrderIdx":3},{"Value":"Trên 1000","IsSelected":false,"id":"","OrderIdx":4}]',
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.01",
    ColCodeSys: "ZaloUserFollowerId",
    NetworkID: "6451164000",
    ColOperatorType: "LIKE",
    OrderIdx: 22,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "ZaloUserFollowerId",
    ColCaption: "ZaloUserFollowerId",
    ColDataType: "ZALOUSERFOLLOWER",
    FlagIsColDynamic: "0",
    SqlOperatorType: "like",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.02",
    ColCodeSys: "CountryCodeContact",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 1,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "CountryCodeContact",
    ColCaption: "Quốc gia (liên hệ)",
    ColDataType: "TEXT",
    FlagIsColDynamic: "0",
    SqlOperatorType: "=",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.02",
    ColCodeSys: "C01L",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 2,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "C01K",
    ColCaption: "Mã bưu chính",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "=",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.02",
    ColCodeSys: "ProvinceCodeContact",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 3,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "ProvinceCodeContact",
    ColCaption: "Tỉnh/Thành (liên hệ)",
    ColDataType: "TEXT",
    FlagIsColDynamic: "0",
    SqlOperatorType: "=",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.02",
    ColCodeSys: "C01N",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 4,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "C01M",
    ColCaption: "Website",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "=",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.02",
    ColCodeSys: "DistrictCodeContact",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 5,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "DistrictCodeContact",
    ColCaption: "Quận/Huyện (liên hệ)",
    ColDataType: "TEXT",
    FlagIsColDynamic: "0",
    SqlOperatorType: "=",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.02",
    ColCodeSys: "C086",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 6,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "C085",
    ColCaption: "Vùng thị trường",
    ColDataType: "MASTERDATA",
    FlagIsColDynamic: "1",
    SqlOperatorType: "=",
    mdmc_JsonListOption: '[{"Value":"Mst_Area"}]',
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.02",
    ColCodeSys: "WardCodeContact",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 7,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "WardCodeContact",
    ColCaption: "Phường/Xã (liên hệ)",
    ColDataType: "TEXT",
    FlagIsColDynamic: "0",
    SqlOperatorType: "=",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.02",
    ColCodeSys: "C01J",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 8,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "C01I",
    ColCaption: "Địa chỉ",
    ColDataType: "TEXTAREA",
    FlagIsColDynamic: "1",
    SqlOperatorType: "=",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.02",
    ColCodeSys: "C065",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 9,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "C062",
    ColCaption: "Số nhà, Đường phố ( Liên hệ)",
    ColDataType: "TEXTAREA",
    FlagIsColDynamic: "1",
    SqlOperatorType: "=",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.023",
    ColCodeSys: "C01T",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 1,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "C01R",
    ColCaption: "Số tài khoản",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "=",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.023",
    ColCodeSys: "C01Z",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 2,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "C01Y",
    ColCaption: "Tài khoản công nợ phải thu",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "=",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.023",
    ColCodeSys: "C01V",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 3,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "C01U",
    ColCaption: "Ngân hàng",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "=",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.023",
    ColCodeSys: "C022",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 4,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "C020",
    ColCaption: "Tài khoản công nợ phải trả",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "=",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.023",
    ColCodeSys: "C01X",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 5,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "C01W",
    ColCaption: "Điều khoản bán hàng",
    ColDataType: "MASTERDATA",
    FlagIsColDynamic: "1",
    SqlOperatorType: "=",
    mdmc_JsonListOption: '[{"Value":"Mst_PaymentTerm"}]',
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.023",
    ColCodeSys: "C024",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 6,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "C023",
    ColCaption: "Điều khoản mua hàng",
    ColDataType: "MASTERDATA",
    FlagIsColDynamic: "1",
    SqlOperatorType: "=",
    mdmc_JsonListOption: '[{"Value":"Mst_PaymentTerm"}]',
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.03",
    ColCodeSys: "CountryCodeInvoice",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 1,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "CountryCodeInvoice",
    ColCaption: "Quốc gia (hóa đơn)",
    ColDataType: "TEXT",
    FlagIsColDynamic: "0",
    SqlOperatorType: "=",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.03",
    ColCodeSys: "ProvinceCodeInvoice",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 2,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "ProvinceCodeInvoice",
    ColCaption: "Tỉnh/Thành (hóa đơn)",
    ColDataType: "TEXT",
    FlagIsColDynamic: "0",
    SqlOperatorType: "=",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.03",
    ColCodeSys: "C026",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 3,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "C025",
    ColCaption: "Tên đơn vị",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "=",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.03",
    ColCodeSys: "DistrictCodeInvoice",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 4,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "DistrictCodeInvoice",
    ColCaption: "Quận/Huyện (hóa đơn)",
    ColDataType: "TEXT",
    FlagIsColDynamic: "0",
    SqlOperatorType: "=",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.03",
    ColCodeSys: "C028",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 5,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "C027",
    ColCaption: "Người mua hàng",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "=",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.03",
    ColCodeSys: "WardCodeInvoice",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 6,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "WardCodeInvoice",
    ColCaption: "Phường/Xã (hóa đơn)",
    ColDataType: "TEXT",
    FlagIsColDynamic: "0",
    SqlOperatorType: "=",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.03",
    ColCodeSys: "C02A",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 7,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "C029",
    ColCaption: "Email nhận HĐ",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "=",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.03",
    ColCodeSys: "C02F",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 8,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "C02E",
    ColCaption: "Số nhà, Đường phố (Hóa đơn)",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "=",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.03",
    ColCodeSys: "C02C",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 9,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "C02B",
    ColCaption: "Địa chỉ đầy đủ (Hóa đơn)",
    ColDataType: "TEXTAREA",
    FlagIsColDynamic: "1",
    SqlOperatorType: "=",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.03",
    ColCodeSys: "C02H",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 10,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "C02G",
    ColCaption: "Mã bưu chính (Hóa đơn)",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "=",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.04",
    ColCodeSys: "CountryCodeDelivery",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 1,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "CountryCodeDelivery",
    ColCaption: "Quốc gia (giao hàng)",
    ColDataType: "TEXT",
    FlagIsColDynamic: "0",
    SqlOperatorType: "=",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.04",
    ColCodeSys: "C02J",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 2,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "C02I",
    ColCaption: "Số nhà, Đường phố (Giao hàng)",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "=",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.04",
    ColCodeSys: "DistrictCodeDelivery",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 3,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "DistrictCodeDelivery",
    ColCaption: "Quận/Huyện (giao hàng)",
    ColDataType: "TEXT",
    FlagIsColDynamic: "0",
    SqlOperatorType: "=",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.04",
    ColCodeSys: "C02M",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 4,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "C02K",
    ColCaption: "Địa chỉ (Giao hàng)",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "=",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.04",
    ColCodeSys: "ProvinceCodeDelivery",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 5,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "ProvinceCodeDelivery",
    ColCaption: "Tỉnh/Thành (giao hàng)",
    ColDataType: "TEXT",
    FlagIsColDynamic: "0",
    SqlOperatorType: "=",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.04",
    ColCodeSys: "C090",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 6,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "C08Z",
    ColCaption: "Mã bưu chính ( Giao hàng)",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "=",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.04",
    ColCodeSys: "WardCodeDelivery",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 7,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "WardCodeDelivery",
    ColCaption: "Phường/Xã (giao hàng)",
    ColDataType: "TEXT",
    FlagIsColDynamic: "0",
    SqlOperatorType: "=",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.05",
    ColCodeSys: "C040",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 1,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "C03Z",
    ColCaption: "Fax",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "=",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.05",
    ColCodeSys: "C046",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 2,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "C045",
    ColCaption: "UserID ( của KH)",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "=",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.05",
    ColCodeSys: "C042",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 3,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "C041",
    ColCaption: "GLN",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "=",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.05",
    ColCodeSys: "C048",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 4,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "C047",
    ColCaption: "OrgID",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "=",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.05",
    ColCodeSys: "C044",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 5,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "C043",
    ColCaption: "Vị trí",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "=",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.05",
    ColCodeSys: "C099",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 6,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "C098",
    ColCaption: "NetworkID",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "=",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.05",
    ColCodeSys: "CustomerAvatarPath",
    NetworkID: "6451164000",
    ColOperatorType: "LIKE",
    OrderIdx: 7,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "CustomerAvatarPath",
    ColCaption: "Đường dẫn ảnh Avatar",
    ColDataType: "IMAGE",
    FlagIsColDynamic: "0",
    SqlOperatorType: "like",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.06",
    ColCodeSys: "UserCodeMng",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 1,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "UserCodeMng",
    ColCaption: "Nhân viên quản lý KH",
    ColDataType: "USERMANAGER",
    FlagIsColDynamic: "0",
    SqlOperatorType: "=",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.06",
    ColCodeSys: "CreateBy",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 2,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "CreateBy",
    ColCaption: "Người tạo",
    ColDataType: "CREATEBY",
    FlagIsColDynamic: "0",
    SqlOperatorType: "=",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.06",
    ColCodeSys: "C09D",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 3,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "C09C",
    ColCaption: "Là khách hàng từ ngày",
    ColDataType: "DATE",
    FlagIsColDynamic: "1",
    SqlOperatorType: "=",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.06",
    ColCodeSys: "CreateDTimeUTC",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 4,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "CreateDTimeUTC",
    ColCaption: "Ngày tạo",
    ColDataType: "CREATEDTIMEUTC",
    FlagIsColDynamic: "0",
    SqlOperatorType: "=",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.06",
    ColCodeSys: "FlagActive",
    NetworkID: "6451164000",
    ColOperatorType: "EQUAL",
    OrderIdx: 5,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:38",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "FlagActive",
    ColCaption: "Trạng thái",
    ColDataType: "TEXT",
    FlagIsColDynamic: "0",
    SqlOperatorType: "=",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
];

const screenContact = [
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "CGCS.CTM.CONTACT.2023",
    ColCodeSys: "CustomerName",
    NetworkID: "6451164000",
    ColOperatorType: "LIKE",
    OrderIdx: 1,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "1",
    FlagIsCheckDuplicate: "1",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:55",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "CustomerName",
    ColCaption: "Tên khách hàng",
    ColDataType: "TEXT",
    FlagIsColDynamic: "0",
    SqlOperatorType: "like",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "CGCS.CTM.CONTACT.2023",
    ColCodeSys: "C005",
    NetworkID: "6451164000",
    ColOperatorType: "LIKE",
    OrderIdx: 2,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "1",
    FlagIsCheckDuplicate: "1",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:55",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "C004",
    ColCaption: "Chức vụ",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "like",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "CGCS.CTM.CONTACT.2023",
    ColCodeSys: "CtmPhoneNo",
    NetworkID: "6451164000",
    ColOperatorType: "LIKE",
    OrderIdx: 3,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "1",
    FlagIsCheckDuplicate: "1",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:55",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "CtmPhoneNo",
    ColCaption: "Phone",
    ColDataType: "PHONE",
    FlagIsColDynamic: "0",
    SqlOperatorType: "like",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "CGCS.CTM.CONTACT.2023",
    ColCodeSys: "CtmEmail",
    NetworkID: "6451164000",
    ColOperatorType: "LIKE",
    OrderIdx: 4,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "1",
    FlagIsCheckDuplicate: "1",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:55",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "CtmEmail",
    ColCaption: "Email",
    ColDataType: "EMAIL",
    FlagIsColDynamic: "0",
    SqlOperatorType: "like",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "CGCS.CTM.CONTACT.2023",
    ColCodeSys: "C01J",
    NetworkID: "6451164000",
    ColOperatorType: "LIKE",
    OrderIdx: 5,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "1",
    FlagIsCheckDuplicate: "1",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:55",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "C01I",
    ColCaption: "Địa chỉ",
    ColDataType: "TEXTAREA",
    FlagIsColDynamic: "1",
    SqlOperatorType: "like",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "6451164000",
    ColGrpCodeSys: "CGCS.CTM.CONTACT.2023",
    ColCodeSys: "C00H",
    NetworkID: "6451164000",
    ColOperatorType: "LIKE",
    OrderIdx: 6,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "1",
    FlagIsCheckDuplicate: "1",
    FlagIsQuery: "1",
    FlagActive: "1",
    LogLUDTimeUTC: "2023-09-16 04:32:55",
    LogLUBy: "0317844394@INOS.VN",
    ColCode: "C00G",
    ColCaption: "Ghi chú",
    ColDataType: "TEXTAREA",
    FlagIsColDynamic: "1",
    SqlOperatorType: "like",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
];

function DemoExcel() {
  const [excelData, setExcelData] = useState(data);

  const { auth } = useAuth();

  const api = useClientgateApi();

  const showError = useSetAtom(showErrorAtom);

  const { t: error } = useI18n("ErrorMessage");

  const handleFileUpload = (event: any) => {
    const file = event.target.files[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (e: any) => {
      const data = new Uint8Array(e.target.result);
      const workbook = XLSX.read(data, { type: "array" });
      const sheetName = workbook.SheetNames[0];
      const sheet = workbook.Sheets[sheetName];
      const jsonData: any = XLSX.utils.sheet_to_json(sheet);

      setExcelData(jsonData);
    };
    reader.readAsArrayBuffer(file);
  };

  const getSql = async () => await api.Seq_GetColCodeSys();

  const handleClearFile = () => {
    setExcelData([]);
  };

  const { data: listDynamic } = useQuery(["listDynamicField"], async () => {
    const resp: any = await api.MDMetaColumn_GetAllActive();

    return resp?.DataList ?? [];
  });

  console.log(jsonData);

  const handleProcess = async () => {
    const listPromise = jsonData.map(async (item: any) => {
      const code = await getSql().then((res) => {
        return res.Data;
      });

      return {
        ColCodeSys: code,
        ColCode: code,
        ...item,
      };
    });

    const result = Promise.all(listPromise).then((res) => res);

    result.then((res) => {
      const listProcess = res.map(async (item: any, index: any) => {
        const param = {
          ...item,
          OrgID: 7410617000,
          NetworkID: 4053894000,
          FlagIsNotNull: "0",
          FlagIsCheckDuplicate: "0",
          FlagIsQuery: "1",
          FlagActive: "1",
          DefaultIndex: "0",
          ColOperatorType: "EQUAL",
          OrderIdx: 0,
        };

        const resp = await api.MDMetaColumn_Create(param);

        if (resp.isSuccess) {
          toast.success(`${param.ColCaption} - thành công!`);
        } else {
          toast.error(`${param.ColCaption} - thất bại!`);
        }
      });

      Promise.all(listProcess).then((res) => res);
    });
  };

  const handleGenDTL = async () => {
    const result = screenDTL.map((item: any) => {
      const found = listDynamic?.find(
        (c: any) => c.ColCaption == item.ColCaption
      );
      if (found) {
        return {
          ...item,
          ColCodeSys: found.ColCodeSys,
          ColCode: found.ColCode,
          OrgID: 6451164000,
          NetworkID: 6451164000,
        };
      }
      return {
        ...item,
        OrgID: 6451164000,
        NetworkID: 6451164000,
      };
    });

    const response = await api.MDMetaColGroupSpec_Save({
      screen: "SCRTCS.CTM.DTL.2023",
      data: result,
    });

    if (response.isSuccess) {
      toast.success(`Insert mã SCRTCS.CTM.DTL.2023 - thành công!`);
    } else {
      showError({
        message: error(response.errorCode),
        debugInfo: response.debugInfo,
        errorInfo: response.errorInfo,
      });
    }
  };

  const handleGenAdd = async () => {
    const result = screenAdd
      .map((item: any) => {
        if (
          item.ColCodeSys == "PartnerType" ||
          item.ColCodeSys == "CustomerType"
        ) {
          return null;
        }

        const found = listDynamic?.find(
          (c: any) => c.ColCaption == item.ColCaption
        );
        if (found) {
          return {
            ...item,
            ColCodeSys: found.ColCodeSys,
            ColCode: found.ColCode,
            OrgID: 7379640000,
            NetworkID: 7379640000,
          };
        }
        return {
          ...item,
          OrgID: 7379640000,
          NetworkID: 7379640000,
        };
      })
      .filter((item: any) => item);

    // console.log(result);
    // return;

    const response = await api.MDMetaColGroupSpec_Save({
      screen: "SCRTPLCODESYS.2023",
      data: result,
    });

    if (response.isSuccess) {
      toast.success(`Insert mã SCRTPLCODESYS.2023 - thành công!`);
    } else {
      showError({
        message: error(response.errorCode),
        debugInfo: response.debugInfo,
        errorInfo: response.errorInfo,
      });
    }
  };

  const handleGenContact = async () => {
    const result = screenContact
      .map((item: any) => {
        const found = listDynamic?.find(
          (c: any) => c.ColCaption == item.ColCaption
        );
        if (found) {
          return {
            ...item,
            ColCodeSys: found.ColCodeSys,
            ColCode: found.ColCode,
            OrgID: 7379640000,
            NetworkID: 7379640000,
          };
        }
        return {
          ...item,
          OrgID: 7379640000,
          NetworkID: 7379640000,
        };
      })
      .filter((item: any) => item);

    // console.log(result);
    // return;

    const response = await api.MDMetaColGroupSpec_Save({
      screen: "SCRTCS.CTM.CONTACT.2023",
      data: result,
    });

    if (response.isSuccess) {
      toast.success(`Insert mã SCRTCS.CTM.CONTACT.2023 - thành công!`);
    } else {
      showError({
        message: error(response.errorCode),
        debugInfo: response.debugInfo,
        errorInfo: response.errorInfo,
      });
    }
  };

  const [translateData] = useAtom(localeAtom);

  const getTranslate = () => {
    let obj = {};

    const viPattern = /[^\x00-\x7F]/;
    const enPattern = /^[a-zA-Z\s]+$/;

    const result = Object.entries(translateData).reduce(
      (prev: any, current: any) => {
        const t = current?.[0];

        let o: any = {};

        const list = current?.[1]?.map((c: any) => {
          // console.log(c);
          if (enPattern.test(c.key) && enPattern.test(c.value)) {
            o[`${String(c.key)}`] = c?.value;
          }

          // o[`${String(c.key)}`] = c?.value;
        });

        prev[`${String(t)}`] = o;

        return prev;
      },
      {}
    );

    const jsonData = JSON.stringify(result);

    // Create a Blob object
    const blob = new Blob([jsonData], { type: "application/json" });

    // Create a link element
    const a = document.createElement("a");

    // Set the download attribute with the desired filename
    a.download = `demo.json`;

    // Create a URL for the Blob and set it as the href attribute of the link
    a.href = window.URL.createObjectURL(blob);

    // Append the link to the document
    document.body.appendChild(a);

    // Trigger a click on the link to start the download
    a.click();

    // Remove the link from the document
    document.body.removeChild(a);
  };

  return (
    <div className="p-2 grid grid-rows-3 gap-2">
      <Button
        onClick={getTranslate}
        style={{
          background: "#00703c",
          color: "#fff",
          padding: "10px 20px",
        }}
        width={400}
      >
        Megred file dich
      </Button>
      {/* <input
        type="file"
        accept=".xlsx, .xls, .csv"
        onChange={handleFileUpload}
      /> */}
      <Button
        onClick={handleProcess}
        style={{
          background: "#00703c",
          color: "#fff",
          padding: "10px 20px",
        }}
        width={400}
      >
        Gen tất cả trường động
      </Button>
      <Button
        onClick={handleGenDTL}
        style={{
          background: "#00703c",
          color: "#fff",
          padding: "10px 20px",
        }}
        width={400}
      >
        Gen mã màn - SCRTCS.CTM.DTL.2023
      </Button>
      <Button
        onClick={handleGenContact}
        style={{
          background: "#00703c",
          color: "#fff",
          padding: "10px 20px",
        }}
        width={400}
      >
        Gen mã màn - SCRTCS.CTM.CONTACT.2023
      </Button>
      <Button
        onClick={handleGenAdd}
        style={{
          background: "#00703c",
          color: "#fff",
          padding: "10px 20px",
        }}
        width={400}
      >
        Gen mã màn - SCRTPLCODESYS.2023
      </Button>
    </div>
  );
}

export default DemoExcel;
