export const ChiTietKhachHangTop = [
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "CGCS.CTM.DTL.2023",
    ColCodeSys: "C0B1",
    NetworkID: "4053894000",
    ColOperatorType: "LIKE",
    OrderIdx: 4,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:07:20",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "C0B0",
    ColCaption: "Chức vụ",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "like",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "CGCS.CTM.DTL.2023",
    ColCodeSys: "CtmEmail",
    NetworkID: "4053894000",
    ColOperatorType: "LIKE",
    OrderIdx: 6,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:07:20",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "CtmEmail",
    ColCaption: "Email",
    ColDataType: "EMAIL",
    FlagIsColDynamic: "0",
    SqlOperatorType: "like",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "CGCS.CTM.DTL.2023",
    ColCodeSys: "CtmPhoneNo",
    NetworkID: "4053894000",
    ColOperatorType: "LIKE",
    OrderIdx: 3,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:07:20",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "CtmPhoneNo",
    ColCaption: "Phone",
    ColDataType: "PHONE",
    FlagIsColDynamic: "0",
    SqlOperatorType: "like",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "CGCS.CTM.DTL.2023",
    ColCodeSys: "CustomerCode",
    NetworkID: "4053894000",
    ColOperatorType: "LIKE",
    OrderIdx: 1,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:07:20",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "CustomerCode",
    ColCaption: "Mã khách hàng",
    ColDataType: "TEXT",
    FlagIsColDynamic: "0",
    SqlOperatorType: "like",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "CGCS.CTM.DTL.2023",
    ColCodeSys: "CustomerCodeSysERP",
    NetworkID: "4053894000",
    ColOperatorType: "EQUAL",
    OrderIdx: 5,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:07:20",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "CustomerCodeSysERP",
    ColCaption: "Doanh nghiệp",
    ColDataType: "CUSTOMERCODESYSERP",
    FlagIsColDynamic: "0",
    SqlOperatorType: "=",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "CGCS.CTM.DTL.2023",
    ColCodeSys: "CustomerName",
    NetworkID: "4053894000",
    ColOperatorType: "LIKE",
    OrderIdx: 2,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:07:20",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "CustomerName",
    ColCaption: "Tên khách hàng",
    ColDataType: "TEXT",
    FlagIsColDynamic: "0",
    SqlOperatorType: "like",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
];
