export const TaoMoiKhachHang = [
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.01",
    ColCodeSys: "C0AM",
    NetworkID: "4053894000",
    ColOperatorType: "LIKE",
    OrderIdx: 7,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "C0AL",
    ColCaption: "Tên viết tắt",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "like",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.01",
    ColCodeSys: "C0AO",
    NetworkID: "4053894000",
    ColOperatorType: "EQUAL",
    OrderIdx: 12,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "C0AN",
    ColCaption: "Nguồn khách",
    ColDataType: "SELECTONEDROPDOWN",
    FlagIsColDynamic: "1",
    SqlOperatorType: "=",
    mdmc_JsonListOption:
      '[{"Value":"Mối quan hệ cá nhân","IsSelected":false,"id":"","OrderIdx":0},{"Value":"Thông qua các công cụ tìm kiếm","IsSelected":false,"id":"","OrderIdx":1},{"Value":"Thông qua hội thảo","IsSelected":false,"id":"","OrderIdx":2},{"Value":"Qua kênh Telesales","IsSelected":false,"id":"","OrderIdx":3},{"Value":"Mạng xã hội","IsSelected":false,"id":"","OrderIdx":4},{"Value":"Nghiên cứu đối thủ cạnh tranh","IsSelected":false,"id":"","OrderIdx":5}]',
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.01",
    ColCodeSys: "C0AV",
    NetworkID: "4053894000",
    ColOperatorType: "EQUAL",
    OrderIdx: 15,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "C0AT",
    ColCaption: "Doanh thu",
    ColDataType: "SELECTONEDROPDOWN",
    FlagIsColDynamic: "1",
    SqlOperatorType: "=",
    mdmc_JsonListOption:
      '[{"Value":"Dưới 3 tỉ đồng","IsSelected":false,"id":"","OrderIdx":0},{"Value":"Từ 3-10 tỉ đồng","IsSelected":false,"id":"","OrderIdx":1},{"Value":"Từ 10 - 100 tỉ đồng","IsSelected":false,"id":"","OrderIdx":2},{"Value":"Trên 100 tỉ đồng","IsSelected":false,"id":"","OrderIdx":3}]',
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.01",
    ColCodeSys: "C0AX",
    NetworkID: "4053894000",
    ColOperatorType: "EQUAL",
    OrderIdx: 13,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "C0AW",
    ColCaption: "Loại hình",
    ColDataType: "SELECTONEDROPDOWN",
    FlagIsColDynamic: "1",
    SqlOperatorType: "=",
    mdmc_JsonListOption:
      '[{"Value":"Công ty trách nhiệm hữu hạn 1 thành viên","IsSelected":false,"id":"","OrderIdx":0},{"Value":"Công ty trách nhiệm hữu hạn 2 thành viên trở lên","IsSelected":false,"id":"","OrderIdx":1},{"Value":"Doanh nghiệp hợp danh","IsSelected":false,"id":"","OrderIdx":2},{"Value":"Công ty cổ phần","IsSelected":false,"id":"","OrderIdx":3},{"Value":"Doanh nghiệp tư nhân","IsSelected":false,"id":"","OrderIdx":4},{"Value":"Doanh nghiệp có trách nhiệm vô hạn","IsSelected":false,"id":"","OrderIdx":5},{"Value":"Doanh nghiệp có trách nhiệm hữu hạn","IsSelected":false,"id":"","OrderIdx":6}]',
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.01",
    ColCodeSys: "C0AZ",
    NetworkID: "4053894000",
    ColOperatorType: "EQUAL",
    OrderIdx: 17,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "C0AY",
    ColCaption: "Quy mô nhân sự",
    ColDataType: "SELECTONEDROPDOWN",
    FlagIsColDynamic: "1",
    SqlOperatorType: "=",
    mdmc_JsonListOption:
      '[{"Value":"Dưới 10","IsSelected":false,"id":"","OrderIdx":0},{"Value":"Từ 10 - 100 ","IsSelected":false,"id":"","OrderIdx":1},{"Value":"Từ 100 - 200","IsSelected":false,"id":"","OrderIdx":2},{"Value":"Từ 200 - 1000","IsSelected":false,"id":"","OrderIdx":3},{"Value":"Trên 1000","IsSelected":false,"id":"","OrderIdx":4}]',
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.01",
    ColCodeSys: "C0B1",
    NetworkID: "4053894000",
    ColOperatorType: "LIKE",
    OrderIdx: 4,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "C0B0",
    ColCaption: "Chức vụ",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "like",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.01",
    ColCodeSys: "C0B3",
    NetworkID: "4053894000",
    ColOperatorType: "EQUAL",
    OrderIdx: 8,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "C0B2",
    ColCaption: "Giới tính",
    ColDataType: "SELECTONERADIO",
    FlagIsColDynamic: "1",
    SqlOperatorType: "=",
    mdmc_JsonListOption:
      '[{"Value":"Nam","IsSelected":true,"id":"","OrderIdx":0},{"Value":"Nữ","IsSelected":false,"id":"","OrderIdx":1},{"Value":"Khác","IsSelected":false,"id":"","OrderIdx":2}]',
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.01",
    ColCodeSys: "C0B6",
    NetworkID: "4053894000",
    ColOperatorType: "RANGE",
    OrderIdx: 10,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "C0B5",
    ColCaption: "Ngày sinh",
    ColDataType: "DATE",
    FlagIsColDynamic: "1",
    SqlOperatorType: "=>;<=",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.01",
    ColCodeSys: "C0BC",
    NetworkID: "4053894000",
    ColOperatorType: "EQUAL",
    OrderIdx: 14,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "C0BB",
    ColCaption: "Ngành nghề",
    ColDataType: "SELECTONEDROPDOWN",
    FlagIsColDynamic: "1",
    SqlOperatorType: "=",
    mdmc_JsonListOption:
      '[{"Value":"Nhóm ngành sản xuất và chế biến","IsSelected":false,"id":"","OrderIdx":0},{"Value":"Nhóm ngành kiến trúc và xây dựng","IsSelected":false,"id":"","OrderIdx":1},{"Value":"Nhóm những ngành kinh doanh","IsSelected":false,"id":"","OrderIdx":2},{"Value":"Nhóm các ngành công nghệ - thông tin","IsSelected":false,"id":"","OrderIdx":3},{"Value":"Nhóm ngành luật - nhân văn","IsSelected":false,"id":"","OrderIdx":4},{"Value":"Nhóm ngành nghệ thuật - thẩm mỹ - đồ họa","IsSelected":false,"id":"","OrderIdx":5},{"Value":"Nhóm ngành báo chí - khoa học và xã hội","IsSelected":false,"id":"","OrderIdx":6},{"Value":"Nhóm ngành khoa học cơ bản","IsSelected":false,"id":"","OrderIdx":7},{"Value":"Nhóm ngành Sư phạm","IsSelected":false,"id":"","OrderIdx":8},{"Value":"Nhóm ngành nông - lâm - ngư nghiệp","IsSelected":false,"id":"","OrderIdx":9}]',
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.01",
    ColCodeSys: "C0BE",
    NetworkID: "4053894000",
    ColOperatorType: "LIKE",
    OrderIdx: 16,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "C0BD",
    ColCaption: "Ghi chú",
    ColDataType: "TEXTAREA",
    FlagIsColDynamic: "1",
    SqlOperatorType: "like",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.02",
    ColCodeSys: "C0BG",
    NetworkID: "4053894000",
    ColOperatorType: "LIKE",
    OrderIdx: 9,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "C0BF",
    ColCaption: "Số nhà, Đường phố",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "like",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.02",
    ColCodeSys: "C0BI",
    NetworkID: "4053894000",
    ColOperatorType: "LIKE",
    OrderIdx: 2,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "C0BH",
    ColCaption: "Mã bưu chính",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "like",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.02",
    ColCodeSys: "C0BK",
    NetworkID: "4053894000",
    ColOperatorType: "LIKE",
    OrderIdx: 4,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "C0BJ",
    ColCaption: "Website",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "like",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.02",
    ColCodeSys: "C0BM",
    NetworkID: "4053894000",
    ColOperatorType: "EQUAL",
    OrderIdx: 6,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "C0BL",
    ColCaption: "Vùng thị trường",
    ColDataType: "MASTERDATA",
    FlagIsColDynamic: "1",
    SqlOperatorType: "=",
    mdmc_JsonListOption: '[{"Value":"Mst_Area"}]',
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.02",
    ColCodeSys: "C0BO",
    NetworkID: "4053894000",
    ColOperatorType: "LIKE",
    OrderIdx: 8,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "C0BN",
    ColCaption: "Địa chỉ",
    ColDataType: "TEXTAREA",
    FlagIsColDynamic: "1",
    SqlOperatorType: "like",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.023",
    ColCodeSys: "C0BQ",
    NetworkID: "4053894000",
    ColOperatorType: "LIKE",
    OrderIdx: 1,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "C0BP",
    ColCaption: "Số tài khoản",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "like",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.023",
    ColCodeSys: "C0BS",
    NetworkID: "4053894000",
    ColOperatorType: "LIKE",
    OrderIdx: 3,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "C0BR",
    ColCaption: "Ngân hàng",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "like",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.023",
    ColCodeSys: "C0BU",
    NetworkID: "4053894000",
    ColOperatorType: "EQUAL",
    OrderIdx: 5,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "C0BT",
    ColCaption: "Điều khoản bán hàng",
    ColDataType: "MASTERDATA",
    FlagIsColDynamic: "1",
    SqlOperatorType: "=",
    mdmc_JsonListOption: '[{"Value":"Mst_PaymentTerm"}]',
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.023",
    ColCodeSys: "C0BW",
    NetworkID: "4053894000",
    ColOperatorType: "LIKE",
    OrderIdx: 2,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "C0BV",
    ColCaption: "Tài khoản công nợ phải thu",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "like",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.023",
    ColCodeSys: "C0BY",
    NetworkID: "4053894000",
    ColOperatorType: "LIKE",
    OrderIdx: 4,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "C0BX",
    ColCaption: "Tài khoản công nợ phải trả",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "like",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.023",
    ColCodeSys: "C0C0",
    NetworkID: "4053894000",
    ColOperatorType: "EQUAL",
    OrderIdx: 6,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "C0BZ",
    ColCaption: "Điều khoản mua hàng",
    ColDataType: "MASTERDATA",
    FlagIsColDynamic: "1",
    SqlOperatorType: "=",
    mdmc_JsonListOption: '[{"Value":"Mst_PaymentTerm"}]',
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.03",
    ColCodeSys: "C0C2",
    NetworkID: "4053894000",
    ColOperatorType: "LIKE",
    OrderIdx: 3,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "C0C1",
    ColCaption: "Tên đơn vị",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "like",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.03",
    ColCodeSys: "C0C4",
    NetworkID: "4053894000",
    ColOperatorType: "LIKE",
    OrderIdx: 5,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "C0C3",
    ColCaption: "Người mua hàng",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "like",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.03",
    ColCodeSys: "C0C6",
    NetworkID: "4053894000",
    ColOperatorType: "LIKE",
    OrderIdx: 7,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "C0C5",
    ColCaption: "Email nhận HĐ",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "like",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.03",
    ColCodeSys: "C0C8",
    NetworkID: "4053894000",
    ColOperatorType: "LIKE",
    OrderIdx: 10,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "C0C7",
    ColCaption: "Địa chỉ đầy đủ (Hóa đơn)",
    ColDataType: "TEXTAREA",
    FlagIsColDynamic: "1",
    SqlOperatorType: "like",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.03",
    ColCodeSys: "C0CA",
    NetworkID: "4053894000",
    ColOperatorType: "LIKE",
    OrderIdx: 9,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "C0C9",
    ColCaption: "Số nhà, Đường phố (Hóa đơn)",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "like",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.03",
    ColCodeSys: "C0CC",
    NetworkID: "4053894000",
    ColOperatorType: "LIKE",
    OrderIdx: 11,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "C0CB",
    ColCaption: "Mã bưu chính (Hóa đơn)",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "like",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.04",
    ColCodeSys: "C0CE",
    NetworkID: "4053894000",
    ColOperatorType: "LIKE",
    OrderIdx: 2,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "C0CD",
    ColCaption: "Số nhà, Đường phố (Giao hàng)",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "like",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.04",
    ColCodeSys: "C0CG",
    NetworkID: "4053894000",
    ColOperatorType: "LIKE",
    OrderIdx: 4,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "C0CF",
    ColCaption: "Địa chỉ (Giao hàng)",
    ColDataType: "TEXTAREA",
    FlagIsColDynamic: "1",
    SqlOperatorType: "like",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.04",
    ColCodeSys: "C0CI",
    NetworkID: "4053894000",
    ColOperatorType: "LIKE",
    OrderIdx: 6,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "C0CH",
    ColCaption: "Mã bưu chính (Giao hàng)",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "like",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.05",
    ColCodeSys: "C0CK",
    NetworkID: "4053894000",
    ColOperatorType: "LIKE",
    OrderIdx: 1,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "C0CJ",
    ColCaption: "Fax",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "like",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.05",
    ColCodeSys: "C0CM",
    NetworkID: "4053894000",
    ColOperatorType: "LIKE",
    OrderIdx: 3,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "C0CL",
    ColCaption: "GLN",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "like",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.05",
    ColCodeSys: "C0CO",
    NetworkID: "4053894000",
    ColOperatorType: "LIKE",
    OrderIdx: 5,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "C0CN",
    ColCaption: "Vị trí",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "like",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.05",
    ColCodeSys: "C0CQ",
    NetworkID: "4053894000",
    ColOperatorType: "LIKE",
    OrderIdx: 2,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "C0CP",
    ColCaption: "UserID ( của KH)",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "like",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.05",
    ColCodeSys: "C0CT",
    NetworkID: "4053894000",
    ColOperatorType: "LIKE",
    OrderIdx: 4,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "C0CS",
    ColCaption: "OrgID",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "like",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.05",
    ColCodeSys: "C0CV",
    NetworkID: "4053894000",
    ColOperatorType: "LIKE",
    OrderIdx: 6,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "C0CU",
    ColCaption: "NetworkID",
    ColDataType: "TEXT",
    FlagIsColDynamic: "1",
    SqlOperatorType: "like",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.06",
    ColCodeSys: "C0CX",
    NetworkID: "4053894000",
    ColOperatorType: "RANGE",
    OrderIdx: 3,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "C0CW",
    ColCaption: "Là khách hàng từ ngày",
    ColDataType: "DATETIME",
    FlagIsColDynamic: "1",
    SqlOperatorType: "=>;<=",
    mdmc_JsonListOption: "[]",
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.02",
    ColCodeSys: "CountryCodeContact",
    NetworkID: "4053894000",
    ColOperatorType: "EQUAL",
    OrderIdx: 1,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "CountryCodeContact",
    ColCaption: "Quốc gia (liên hệ)",
    ColDataType: "TEXT",
    FlagIsColDynamic: "0",
    SqlOperatorType: "=",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.04",
    ColCodeSys: "CountryCodeDelivery",
    NetworkID: "4053894000",
    ColOperatorType: "EQUAL",
    OrderIdx: 1,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "CountryCodeDelivery",
    ColCaption: "Quốc gia (giao hàng)",
    ColDataType: "TEXT",
    FlagIsColDynamic: "0",
    SqlOperatorType: "=",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.03",
    ColCodeSys: "CountryCodeInvoice",
    NetworkID: "4053894000",
    ColOperatorType: "EQUAL",
    OrderIdx: 2,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "CountryCodeInvoice",
    ColCaption: "Quốc gia (hóa đơn)",
    ColDataType: "TEXT",
    FlagIsColDynamic: "0",
    SqlOperatorType: "=",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.06",
    ColCodeSys: "CreateBy",
    NetworkID: "4053894000",
    ColOperatorType: "RANGE",
    OrderIdx: 2,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "CreateBy",
    ColCaption: "Người tạo",
    ColDataType: "CREATEBY",
    FlagIsColDynamic: "0",
    SqlOperatorType: "=>;<=",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.06",
    ColCodeSys: "CreateDTimeUTC",
    NetworkID: "4053894000",
    ColOperatorType: "RANGE",
    OrderIdx: 4,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "CreateDTimeUTC",
    ColCaption: "Ngày tạo",
    ColDataType: "CREATEDTIMEUTC",
    FlagIsColDynamic: "0",
    SqlOperatorType: "=>;<=",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.01",
    ColCodeSys: "CtmEmail",
    NetworkID: "4053894000",
    ColOperatorType: "LIKE",
    OrderIdx: 19,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "CtmEmail",
    ColCaption: "Email",
    ColDataType: "EMAIL",
    FlagIsColDynamic: "0",
    SqlOperatorType: "like",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.01",
    ColCodeSys: "CtmPhoneNo",
    NetworkID: "4053894000",
    ColOperatorType: "LIKE",
    OrderIdx: 21,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "CtmPhoneNo",
    ColCaption: "Phone",
    ColDataType: "PHONE",
    FlagIsColDynamic: "0",
    SqlOperatorType: "like",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.05",
    ColCodeSys: "CustomerAvatarPath",
    NetworkID: "4053894000",
    ColOperatorType: "LIKE",
    OrderIdx: 7,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "CustomerAvatarPath",
    ColCaption: "Đường dẫn ảnh Avatar",
    ColDataType: "IMAGE",
    FlagIsColDynamic: "0",
    SqlOperatorType: "like",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.01",
    ColCodeSys: "CustomerCode",
    NetworkID: "4053894000",
    ColOperatorType: "LIKE",
    OrderIdx: 3,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "1",
    FlagIsCheckDuplicate: "1",
    FlagIsQuery: "0",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "CustomerCode",
    ColCaption: "Mã khách hàng",
    ColDataType: "TEXT",
    FlagIsColDynamic: "0",
    SqlOperatorType: "like",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.03",
    ColCodeSys: "CustomerCodeInvoice",
    NetworkID: "4053894000",
    ColOperatorType: "LIKE",
    OrderIdx: 1,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "CustomerCodeInvoice",
    ColCaption: "Mã Khách hàng hóa đơn",
    ColDataType: "TEXT",
    FlagIsColDynamic: "0",
    SqlOperatorType: "like",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.01",
    ColCodeSys: "CustomerCodeSysERP",
    NetworkID: "4053894000",
    ColOperatorType: "EQUAL",
    OrderIdx: 6,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "CustomerCodeSysERP",
    ColCaption: "Doanh nghiệp",
    ColDataType: "CUSTOMERCODESYSERP",
    FlagIsColDynamic: "0",
    SqlOperatorType: "=",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.01",
    ColCodeSys: "CustomerGrpCode",
    NetworkID: "4053894000",
    ColOperatorType: "EQUAL",
    OrderIdx: 11,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "CustomerGrpCode",
    ColCaption: "Nhóm khách hàng",
    ColDataType: "CUSTOMERGROUP",
    FlagIsColDynamic: "0",
    SqlOperatorType: "=",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.01",
    ColCodeSys: "CustomerName",
    NetworkID: "4053894000",
    ColOperatorType: "LIKE",
    OrderIdx: 5,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "1",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "CustomerName",
    ColCaption: "Tên khách hàng",
    ColDataType: "TEXT",
    FlagIsColDynamic: "0",
    SqlOperatorType: "like",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.01",
    ColCodeSys: "CustomerType",
    NetworkID: "4053894000",
    ColOperatorType: "EQUAL",
    OrderIdx: 1,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "1",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "CustomerType",
    ColCaption: "Loại khách hàng",
    ColDataType: "CUSTOMERTYPE",
    FlagIsColDynamic: "0",
    SqlOperatorType: "=",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.02",
    ColCodeSys: "DistrictCodeContact",
    NetworkID: "4053894000",
    ColOperatorType: "EQUAL",
    OrderIdx: 5,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "DistrictCodeContact",
    ColCaption: "Quận/Huyện (liên hệ)",
    ColDataType: "TEXT",
    FlagIsColDynamic: "0",
    SqlOperatorType: "=",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.04",
    ColCodeSys: "DistrictCodeDelivery",
    NetworkID: "4053894000",
    ColOperatorType: "EQUAL",
    OrderIdx: 5,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "DistrictCodeDelivery",
    ColCaption: "Quận/Huyện (giao hàng)",
    ColDataType: "TEXT",
    FlagIsColDynamic: "0",
    SqlOperatorType: "=",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.03",
    ColCodeSys: "DistrictCodeInvoice",
    NetworkID: "4053894000",
    ColOperatorType: "EQUAL",
    OrderIdx: 6,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "DistrictCodeInvoice",
    ColCaption: "Quận/Huyện (hóa đơn)",
    ColDataType: "TEXT",
    FlagIsColDynamic: "0",
    SqlOperatorType: "=",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.06",
    ColCodeSys: "FlagActive",
    NetworkID: "4053894000",
    ColOperatorType: "EQUAL",
    OrderIdx: 5,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "FlagActive",
    ColCaption: "Trạng thái",
    ColDataType: "TEXT",
    FlagIsColDynamic: "0",
    SqlOperatorType: "=",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.01",
    ColCodeSys: "GovID",
    NetworkID: "4053894000",
    ColOperatorType: "LIKE",
    OrderIdx: 18,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "GovID",
    ColCaption: "Số giấy tờ",
    ColDataType: "GOVID",
    FlagIsColDynamic: "0",
    SqlOperatorType: "like",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.01",
    ColCodeSys: "MST",
    NetworkID: "4053894000",
    ColOperatorType: "LIKE",
    OrderIdx: 9,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "MST",
    ColCaption: "MST",
    ColDataType: "TEXT",
    FlagIsColDynamic: "0",
    SqlOperatorType: "like",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.01",
    ColCodeSys: "PartnerType",
    NetworkID: "4053894000",
    ColOperatorType: "EQUAL",
    OrderIdx: 2,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "1",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "PartnerType",
    ColCaption: "Đối Tượng",
    ColDataType: "PARTNERTYPE",
    FlagIsColDynamic: "0",
    SqlOperatorType: "=",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.02",
    ColCodeSys: "ProvinceCodeContact",
    NetworkID: "4053894000",
    ColOperatorType: "EQUAL",
    OrderIdx: 3,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "ProvinceCodeContact",
    ColCaption: "Tỉnh/Thành (liên hệ)",
    ColDataType: "TEXT",
    FlagIsColDynamic: "0",
    SqlOperatorType: "=",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.04",
    ColCodeSys: "ProvinceCodeDelivery",
    NetworkID: "4053894000",
    ColOperatorType: "EQUAL",
    OrderIdx: 3,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "ProvinceCodeDelivery",
    ColCaption: "Tỉnh/Thành (giao hàng)",
    ColDataType: "TEXT",
    FlagIsColDynamic: "0",
    SqlOperatorType: "=",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.03",
    ColCodeSys: "ProvinceCodeInvoice",
    NetworkID: "4053894000",
    ColOperatorType: "EQUAL",
    OrderIdx: 4,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "ProvinceCodeInvoice",
    ColCaption: "Tỉnh/Thành (hóa đơn)",
    ColDataType: "TEXT",
    FlagIsColDynamic: "0",
    SqlOperatorType: "=",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.06",
    ColCodeSys: "UserCodeMng",
    NetworkID: "4053894000",
    ColOperatorType: "EQUAL",
    OrderIdx: 1,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "UserCodeMng",
    ColCaption: "Nhân viên quản lý KH",
    ColDataType: "USERMANAGER",
    FlagIsColDynamic: "0",
    SqlOperatorType: "=",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.02",
    ColCodeSys: "WardCodeContact",
    NetworkID: "4053894000",
    ColOperatorType: "EQUAL",
    OrderIdx: 7,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "WardCodeContact",
    ColCaption: "Phường/Xã (liên hệ)",
    ColDataType: "TEXT",
    FlagIsColDynamic: "0",
    SqlOperatorType: "=",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.04",
    ColCodeSys: "WardCodeDelivery",
    NetworkID: "4053894000",
    ColOperatorType: "EQUAL",
    OrderIdx: 7,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "WardCodeDelivery",
    ColCaption: "Phường/Xã (giao hàng)",
    ColDataType: "TEXT",
    FlagIsColDynamic: "0",
    SqlOperatorType: "=",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.03",
    ColCodeSys: "WardCodeInvoice",
    NetworkID: "4053894000",
    ColOperatorType: "EQUAL",
    OrderIdx: 8,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "WardCodeInvoice",
    ColCaption: "Phường/Xã (hóa đơn)",
    ColDataType: "TEXT",
    FlagIsColDynamic: "0",
    SqlOperatorType: "=",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
  {
    OrgID: "4053894000",
    ColGrpCodeSys: "COLGRPCODESYS.2023.01",
    ColCodeSys: "ZaloUserFollowerId",
    NetworkID: "4053894000",
    ColOperatorType: "LIKE",
    OrderIdx: 20,
    JsonRenderParams: null,
    JsonListOption: null,
    FlagIsNotNull: "0",
    FlagIsCheckDuplicate: "0",
    FlagIsQuery: "1",
    FlagActive: true,
    LogLUDTimeUTC: "2024-01-03 10:05:54",
    LogLUBy: "anhntp@longquang.vn",
    ColCode: "ZaloUserFollowerId",
    ColCaption: "ZaloUserFollowerId",
    ColDataType: "ZALOUSERFOLLOWER",
    FlagIsColDynamic: "0",
    SqlOperatorType: "like",
    mdmc_JsonListOption: null,
    Lst_MD_OptionValue: null,
  },
];
